### ISSUE TITLE
Add Navigation Bar

### ISSUE THREAD

**Issue by SatyaRajAwasth1** [noskofficial/sfd-website#4]
- [x] Landing page will contain navigation bar which will be reusable in other pages too.
- [x] Current section / page will be highlighted

Sample view: 

![image](https://github.com/user-attachments/assets/8dce0f0c-e121-4a6b-9fad-5bb9c894a2c4)

**Comment by anishkn04** [comment]
Navbar Preview:
![image](https://github.com/user-attachments/assets/4cb4d0df-a069-43f9-a658-2267c91bb24d)

To attach navbar in any page:
1. Add id "body" to the body element
2. Add: `<script src="../js/navbar.js"></script>` at the end of the file
3. Add: `<link rel="stylesheet" href="../css/output.css">` as well

`npm run dev` to generate the output.css
